### PR TITLE
Bring up to date

### PR DESCRIPTION
**Pull request by peppy**
Remaining work to be done:

- Re-export fonts using binary bmfont format.
- Check all functionality still works.

### CODE REVIEW

**Comment by sr229** [comment]
Hey @peppy, thanks for the contribution, but this is a code from our very bygone era and we don't plan to maintain this. Should you wish to contribute again, everything will be done in LovewingCore because we have to redesign the core to be in line with our new design specifications.

I'll be closing this for now. Thank you!

**Comment by peppy** [comment]
no problem. just wanted to show that this could be done in roughly 10 minutes. you may find my branch useful if you plan on migrating any of your classes across (they still seem quite usable).

**Comment by sr229** [comment]
I'll keep that in mind @peppy, thank you ❤️

**Comment by sr229** [comment]
Reopening this to serve as a baseline for refactoring, merging.

**Pull request merged**
